# Generated by Django 6.1 on 2026-09-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
