# Generated by Django 6.1 on 2026-09-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
